import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Asset management",
  description: "Generated by Avishkar Gadkar"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Toaster 
          position="top-right"
          toastOptions={{
            duration: 4000,
            style: {
              background: '#333',
              color: '#fff',
            },
            success: {
              style: {
                background: '#1e293b',
                border: '1px solid #0d9488',
                color: '#fff',
              },
              iconTheme: {
                primary: '#0d9488',
                secondary: '#fff',
              },
            },
            error: {
              style: {
                background: '#1e293b',
                border: '1px solid #ef4444',
                color: '#fff',
              },
              iconTheme: {
                primary: '#ef4444',
                secondary: '#fff',
              },
            },
          }}
        />
      </body>
    </html>
  );
}